import { colors } from './colors';

export const spacing = {
  xs: 4,
  sm: 8,
  md: 16,
  lg: 24,
  xl: 32,
  xxl: 48,
} as const;

export const radius = {
  sm: 4,
  md: 8,
  lg: 12,
  xl: 16,
  full: 999,
} as const;

export const typography = {
  mono: {
    fontFamily: 'JetBrainsMono-Regular',
    fontSize: 13,
    lineHeight: 20,
  letterSpacing: 0.3,
  color: colors.textPrimary,
  weight: '400' as const,
  style: 'normal' as const,
  variant: undefined as undefined,
    includeFontPadding: false,
    fontFamilyFallback: ['monospace', 'Courier New'],
  textTransform: 'none' as const,
  textDecorationLine: 'none' as const,
    textAlign: 'left' as const,
    textAlignVertical: 'auto' as const,
    fontStyle: 'normal' as const,
  },
  monoBold: {
    fontFamily: 'JetBrainsMono-Bold',
    fontSize: 13,
    lineHeight: 20,
    letterSpacing: 0.3,
    color: colors.textPrimary,
    weight: '700' as const,
    style: 'normal' as const,
    variant: undefined as undefined,
    includeFontPadding: false,
    fontFamilyFallback: ['monospace', 'Courier New'],
    textTransform: 'none' as const,
    textDecorationLine: 'none' as const,
    textAlign: 'left' as const,
    textAlignVertical: 'auto' as const,
    fontStyle: 'normal' as const,
  },
  monoSmall: {
    fontFamily: 'JetBrainsMono-Regular',
    fontSize: 11,
    lineHeight: 16,
    letterSpacing: 0.3,
    color: colors.textSecondary,
    weight: '400' as const,
    style: 'normal' as const,
    variant: undefined as undefined,
    includeFontPadding: false,
    fontFamilyFallback: ['monospace', 'Courier New'],
    textTransform: 'none' as const,
    textDecorationLine: 'none' as const,
    textAlign: 'left' as const,
    textAlignVertical: 'auto' as const,
    fontStyle: 'normal' as const,
  },
  sans: {
    fontFamily: 'Inter-Regular',
    fontSize: 15,
    lineHeight: 22,
    letterSpacing: 0,
    color: colors.textPrimary,
    weight: '400' as const,
    style: 'normal' as const,
    variant: undefined as undefined,
    includeFontPadding: false,
    fontFamilyFallback: ['sans-serif'],
    textTransform: 'none' as const,
    textDecorationLine: 'none' as const,
    textAlign: 'left' as const,
    textAlignVertical: 'auto' as const,
    fontStyle: 'normal' as const,
  },
  sansBold: {
    fontFamily: 'Inter-Bold',
    fontSize: 15,
    lineHeight: 22,
    letterSpacing: 0,
    color: colors.textPrimary,
    weight: '700' as const,
    style: 'normal' as const,
    variant: undefined as undefined,
    includeFontPadding: false,
    fontFamilyFallback: ['sans-serif'],
    textTransform: 'none' as const,
    textDecorationLine: 'none' as const,
    textAlign: 'left' as const,
    textAlignVertical: 'auto' as const,
    fontStyle: 'normal' as const,
  },
  caption: {
    fontFamily: 'Inter-Regular',
    fontSize: 12,
    lineHeight: 18,
    letterSpacing: 0,
    color: colors.textSecondary,
    weight: '400' as const,
    style: 'normal' as const,
    variant: undefined as undefined,
    includeFontPadding: false,
    fontFamilyFallback: ['sans-serif'],
    textTransform: 'none' as const,
    textDecorationLine: 'none' as const,
    textAlign: 'left' as const,
    textAlignVertical: 'auto' as const,
    fontStyle: 'normal' as const,
  },
  title: {
    fontFamily: 'Inter-Bold',
    fontSize: 20,
    lineHeight: 28,
    letterSpacing: -0.3,
    color: colors.textPrimary,
    weight: '700' as const,
    style: 'normal' as const,
    variant: undefined as undefined,
    includeFontPadding: false,
    fontFamilyFallback: ['sans-serif'],
    textTransform: 'none' as const,
    textDecorationLine: 'none' as const,
    textAlign: 'left' as const,
    textAlignVertical: 'auto' as const,
    fontStyle: 'normal' as const,
  },
  sectionHeader: {
    fontFamily: 'JetBrainsMono-Bold',
    fontSize: 11,
    lineHeight: 16,
    letterSpacing: 1.5,
    color: colors.textTertiary,
    weight: '700' as const,
    style: 'normal' as const,
    variant: undefined as undefined,
    includeFontPadding: false,
    fontFamilyFallback: ['monospace', 'Courier New'],
    textTransform: 'uppercase' as const,
    textDecorationLine: 'none' as const,
    textAlign: 'left' as const,
    textAlignVertical: 'auto' as const,
    fontStyle: 'normal' as const,
  },
} as const;

export type TypographyKey = keyof typeof typography;
export type TextStyle = typeof typography.mono;

export const layout = {
  tabBarHeight: 58,
  topBarHeight: 52,
  panelPadding: 16,
  cardPadding: 14,
} as const;

export const theme = {
  colors,
  spacing,
  radius,
  typography,
  layout,
} as const;

export default theme;
