import type { Feature } from '@/types';

export const features: Feature[] = [
  {
    id: 'aimbot',
    index: 1,
    name: 'Aimbot Precision',
    shortName: 'Aimbot',
    description: 'Auto-lock crosshair to enemy hitboxes with adjustable FOV and smoothness. Silent aim bypasses server-side detection.',
    category: 'behavior',
    riskLevel: 'critical',
    status: 'disabled',
    icon: 'Fingerprint',
    isSimulated: false,
    isEducational: false,
    isAbstract: false,
  },
  {
    id: 'esp-wallhack',
    index: 2,
    name: 'ESP / Wallhack',
    shortName: 'ESP',
    description: 'Render enemy positions, health, distance, and loot through walls. Box, skeleton, and line modes.',
    category: 'behavior',
    riskLevel: 'critical',
    status: 'disabled',
    icon: 'Eye',
    isSimulated: false,
    isEducational: false,
    isAbstract: false,
  },
  {
    id: 'speed-hack',
    index: 3,
    name: 'Speed Hack',
    shortName: 'Speed',
    description: 'Multiply player movement speed while staying under server thresholds. Sprint, walk, and prone modifiers.',
    category: 'behavior',
    riskLevel: 'critical',
    status: 'disabled',
    icon: 'Zap',
    isSimulated: false,
    isEducational: false,
    isAbstract: false,
  },
  {
    id: 'recoil-control',
    index: 4,
    name: 'Recoil Control',
    shortName: 'Recoil',
    description: 'Eliminate vertical and horizontal recoil patterns for all weapons. Per-gun tuning profiles.',
    category: 'behavior',
    riskLevel: 'high',
    status: 'disabled',
    icon: 'TrendingDown',
    isSimulated: false,
    isEducational: false,
    isAbstract: false,
  },
  {
    id: 'magic-bullet',
    index: 5,
    name: 'Magic Bullet',
    shortName: 'Magic',
    description: 'Redirect projectiles to nearest enemy target. Hit registration manipulation.',
    category: 'behavior',
    riskLevel: 'critical',
    status: 'disabled',
    icon: 'Sparkles',
    isSimulated: false,
    isEducational: false,
    isAbstract: false,
  },
  {
    id: 'no-recoil',
    index: 6,
    name: 'No Recoil',
    shortName: 'NoRecoil',
    description: 'Zero recoil on all weapons. Crosshair stays perfectly centered during sustained fire.',
    category: 'behavior',
    riskLevel: 'critical',
    status: 'disabled',
    icon: 'Activity',
    isSimulated: false,
    isEducational: false,
    isAbstract: false,
  },
  {
    id: 'instant-hit',
    index: 7,
    name: 'Instant Hit',
    shortName: 'InstantHit',
    description: 'Hitscan conversion — bullets register on the same frame as the shot. No travel time.',
    category: 'behavior',
    riskLevel: 'critical',
    status: 'disabled',
    icon: 'Zap',
    isSimulated: false,
    isEducational: false,
    isAbstract: false,
  },
  {
    id: 'auto-headshot',
    index: 8,
    name: 'Auto Headshot',
    shortName: 'AutoHS',
    description: 'Force all shots to register as headshots. Bypasses hitbox validation on server.',
    category: 'behavior',
    riskLevel: 'critical',
    status: 'disabled',
    icon: 'Fingerprint',
    isSimulated: false,
    isEducational: false,
    isAbstract: false,
  },
  {
    id: 'radar-hack',
    index: 9,
    name: 'Radar Hack',
    shortName: 'Radar',
    description: 'Full map awareness — show all players, vehicles, and loot on minimap in real time.',
    category: 'intelligence',
    riskLevel: 'high',
    status: 'disabled',
    icon: 'Network',
    isSimulated: false,
    isEducational: false,
    isAbstract: false,
  },
  {
    id: 'item-esp',
    index: 10,
    name: 'Item ESP',
    shortName: 'ItemESP',
    description: 'Highlight high-tier loot through walls with distance and name labels.',
    category: 'intelligence',
    riskLevel: 'high',
    status: 'disabled',
    icon: 'Box',
    isSimulated: false,
    isEducational: false,
    isAbstract: false,
  },
  {
    id: 'vehicle-esp',
    index: 11,
    name: 'Vehicle ESP',
    shortName: 'VehESP',
    description: 'Show all vehicles, their fuel, health, and distance through terrain.',
    category: 'intelligence',
    riskLevel: 'medium',
    status: 'disabled',
    icon: 'Share2',
    isSimulated: false,
    isEducational: false,
    isAbstract: false,
  },
  {
    id: 'grenade-helper',
    index: 12,
    name: 'Grenade Helper',
    shortName: 'Nade',
    description: 'Trajectory prediction for grenades with bounce simulation and landing marker.',
    category: 'behavior',
    riskLevel: 'medium',
    status: 'disabled',
    icon: 'Share',
    isSimulated: false,
    isEducational: false,
    isAbstract: false,
  },
  {
    id: 'anti-recoil-pro',
    index: 13,
    name: 'Anti-Recoil Pro',
    shortName: 'AntiRecoil',
    description: 'Advanced recoil compensation with weapon-specific patterns and burst control.',
    category: 'behavior',
    riskLevel: 'high',
    status: 'disabled',
    icon: 'Gauge',
    isSimulated: false,
    isEducational: false,
    isAbstract: false,
  },
  {
    id: 'fast-loot',
    index: 14,
    name: 'Fast Loot',
    shortName: 'FastLoot',
    description: 'Instant pickup — loot items are collected the moment you aim at them.',
    category: 'behavior',
    riskLevel: 'high',
    status: 'disabled',
    icon: 'Download',
    isSimulated: false,
    isEducational: false,
    isAbstract: false,
  },
  {
    id: 'no-reload',
    index: 15,
    name: 'No Reload',
    shortName: 'NoReload',
    description: 'Infinite ammo — no reload animation, magazine never depletes.',
    category: 'behavior',
    riskLevel: 'critical',
    status: 'disabled',
    icon: 'RefreshCw',
    isSimulated: false,
    isEducational: false,
    isAbstract: false,
  },
  {
    id: 'wall-shoot',
    index: 16,
    name: 'Wall Shoot',
    shortName: 'WallShoot',
    description: 'Bullets penetrate all surfaces. Shoot through buildings, rocks, and vehicles.',
    category: 'behavior',
    riskLevel: 'critical',
    status: 'disabled',
    icon: 'ShieldHalf',
    isSimulated: false,
    isEducational: false,
    isAbstract: false,
  },
  {
    id: 'teleport',
    index: 17,
    name: 'Teleport',
    shortName: 'Teleport',
    description: 'Instant position change to any map coordinate. Bypasses movement validation.',
    category: 'behavior',
    riskLevel: 'critical',
    status: 'disabled',
    icon: 'Globe',
    isSimulated: false,
    isEducational: false,
    isAbstract: false,
  },
  {
    id: 'fly-hack',
    index: 18,
    name: 'Fly Hack',
    shortName: 'Fly',
    description: 'Vertical movement — ascend, descend, and hover. No fall damage.',
    category: 'behavior',
    riskLevel: 'critical',
    status: 'disabled',
    icon: 'Cloud',
    isSimulated: false,
    isEducational: false,
    isAbstract: false,
  },
  {
    id: 'invisible',
    index: 19,
    name: 'Invisible',
    shortName: 'Invis',
    description: 'Player model cloaking — enemies cannot see or target you.',
    category: 'behavior',
    riskLevel: 'critical',
    status: 'disabled',
    icon: 'EyeOff',
    isSimulated: false,
    isEducational: false,
    isAbstract: false,
  },
  {
    id: 'god-mode',
    index: 20,
    name: 'God Mode',
    shortName: 'GodMode',
    description: 'Invincibility — zero damage taken from all sources. Health never depletes.',
    category: 'behavior',
    riskLevel: 'critical',
    status: 'disabled',
    icon: 'ShieldCheck',
    isSimulated: false,
    isEducational: false,
    isAbstract: false,
  },
  {
    id: 'unlock-all',
    index: 21,
    name: 'Unlock All',
    shortName: 'Unlock',
    description: 'Unlock all skins, outfits, weapon finishes, and battle pass rewards locally.',
    category: 'accounts',
    riskLevel: 'medium',
    status: 'disabled',
    icon: 'KeyRound',
    isSimulated: false,
    isEducational: false,
    isAbstract: false,
  },
  {
    id: 'rank-spoof',
    index: 22,
    name: 'Rank Spoof',
    shortName: 'RankSpoof',
    description: 'Display any rank and tier in lobbies. Visual only — no server-side change.',
    category: 'accounts',
    riskLevel: 'medium',
    status: 'disabled',
    icon: 'Layers',
    isSimulated: false,
    isEducational: false,
    isAbstract: false,
  },
  {
    id: 'anti-ban',
    index: 23,
    name: 'Anti-Ban Shield',
    shortName: 'AntiBan',
    description: 'Signature randomization, memory cloaking, and behavioral mimicry to evade detection.',
    category: 'forensics',
    riskLevel: 'critical',
    status: 'disabled',
    icon: 'Lock',
    isSimulated: false,
    isEducational: false,
    isAbstract: false,
  },
];

export function getFeatureById(id: string): Feature | undefined {
  return features.find((f) => f.id === id);
}
